# Generated by Django 3.1.4 on 2021-02-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='end',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='mode',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='start',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
